all: lab52Exe

lab52Exe: main_lab52.o class_lab52.o
	g++ -Wall -g -o lab52Exe main_lab52.o class_lab52.o

lab52Obj: main_lab52.cpp
	g++ -Wall -g -c main_lab52.cpp

lab52ClassObj: class_lab52.cpp
	g++ -Wall -g -c class_lab52.cpp